# Generated by Django 5.2.9 on 2025-12-03 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientTicker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_text', models.CharField(default='SYSTEM STATUS: OPTIMAL // 2025.Q4', max_length=100)),
                ('main_heading_line_1', models.CharField(default='BEYOND', max_length=100)),
                ('main_heading_gradient_text', models.CharField(default='HUMANITY', max_length=100)),
                ('sub_text', models.TextField(default='We engineer the post-human enterprise...')),
                ('btn_primary_text', models.CharField(default='INITIATE PROTOCOL', max_length=50)),
                ('btn_secondary_text', models.CharField(default='VIEW CAPABILITIES', max_length=50)),
                ('coord_text', models.CharField(default='COORD: 23.0225° N, 72.5714° E', max_length=100)),
                ('mem_text', models.CharField(default='MEM: 64TB / 128TB', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LabExperiment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon_name', models.CharField(default='flask-conical', max_length=50)),
                ('progress_percent', models.IntegerField(default=50)),
                ('color_class', models.CharField(default='text-purple-500', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tech_stack', models.CharField(help_text='e.g. React • Rust', max_length=100)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='projects/')),
                ('color_class', models.CharField(default='text-alien', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(help_text="Lucide icon name (e.g., 'code-2', 'zap', 'users')", max_length=50)),
                ('module_id', models.CharField(default='MOD_01', max_length=20)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('features_list', models.TextField(help_text='Enter features on separate lines')),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='ALIENHOUSE', max_length=100)),
                ('logo_highlight_text', models.CharField(default='HOUSE', max_length=100)),
                ('address', models.CharField(default='Rajkot, Gujarat, India', max_length=200)),
                ('email', models.EmailField(default='signal@alienhouse.net', max_length=254)),
                ('phone', models.CharField(default='+91 999-999-9999', max_length=50)),
                ('footer_text', models.CharField(default='Galactic Rights Reserved.', max_length=200)),
            ],
            options={
                'verbose_name': 'Site Configuration',
            },
        ),
        migrations.CreateModel(
            name='TacticalAdvantage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon_name', models.CharField(default='zap', max_length=50)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('role', models.CharField(help_text='e.g. COMMANDER', max_length=100)),
                ('job_title', models.CharField(help_text='e.g. CHIEF ARCHITECT', max_length=100)),
                ('image', models.ImageField(upload_to='team/')),
                ('color_class', models.CharField(default='text-alien', help_text='Tailwind color class (e.g. text-alien, text-purple-500)', max_length=50)),
                ('border_color_class', models.CharField(default='border-alien', help_text='Tailwind border class', max_length=50)),
                ('skill_name', models.CharField(default='NEURAL NETS', max_length=50)),
                ('skill_percent', models.IntegerField(default=99)),
                ('order', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
