# Generated by Django 5.2.9 on 2025-12-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_businessteammember_companyprofile_contactmessage_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subservice',
            name='duration_minutes',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='features',
        ),
        migrations.RemoveField(
            model_name='subservice',
            name='price',
        ),
        migrations.AddField(
            model_name='service',
            name='advantage_1',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='advantage_2',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='advantage_3',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='service',
            name='hero_image',
            field=models.ImageField(blank=True, null=True, upload_to='services/hero/'),
        ),
        migrations.AddField(
            model_name='service',
            name='technical_specs',
            field=models.TextField(blank=True, help_text='Technical details or tech stack'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='delivery_time',
            field=models.CharField(blank=True, help_text="e.g. '2 Weeks'", max_length=100),
        ),
        migrations.AddField(
            model_name='subservice',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='subservice',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='services/sub_services/'),
        ),
        migrations.AddField(
            model_name='subservice',
            name='is_popular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='subservice',
            name='price_range',
            field=models.CharField(blank=True, help_text="e.g. '$500 - $1000'", max_length=100),
        ),
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(help_text='Main content for the detail page'),
        ),
        migrations.AlterField(
            model_name='service',
            name='icon',
            field=models.CharField(blank=True, help_text="Lucide icon name (e.g. 'cpu', 'shield')", max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='service',
            name='short_description',
            field=models.CharField(help_text='Shown on cards/lists', max_length=300),
        ),
    ]
