# Generated by Django 5.2.9 on 2025-12-04 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_subservice_duration_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='service_image',
            field=models.ImageField(blank=True, help_text='Main image for the service', null=True, upload_to='services/main/'),
        ),
    ]
