# Generated by Django 5.2.9 on 2025-12-04 16:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_service_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicemodule',
            name='sub_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='core.subservice'),
        ),
    ]
