# Generated by Django 5.2.9 on 2025-12-06 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_aboutus_clientlogo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_type', models.CharField(choices=[('email', 'Email'), ('phone', 'Phone'), ('twitter', 'Twitter'), ('linkedin', 'LinkedIn'), ('facebook', 'Facebook'), ('instagram', 'Instagram'), ('youtube', 'YouTube')], max_length=50)),
                ('display_value', models.CharField(help_text='Text to show, e.g., email address or username', max_length=255)),
                ('link', models.URLField(blank=True, help_text='Link to profile or use mailto: for email, tel: for phone', null=True)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='FooterLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('url', models.URLField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.CharField(choices=[('services', 'Services'), ('company', 'Company'), ('social', 'Social')], max_length=50)),
                ('icon_name', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'ordering': ['category', 'order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='AlienHouse', max_length=100)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='logos/')),
                ('footer_text', models.TextField(default='© 2025 AlienHouse Networks. All Systems Nominal.')),
                ('default_logo_url', models.CharField(default='/static/images/default_logo.png', max_length=255)),
            ],
        ),
    ]
