# Generated by Django 5.2.9 on 2025-12-06 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_contactinfo_footerlink_sitesettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Page title shown in the menu', max_length=100)),
                ('slug', models.SlugField(help_text='URL slug for this page', unique=True)),
                ('url', models.URLField(blank=True, help_text='Optional: external URL. Leave empty for internal pages', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Show or hide in the menu')),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in the dropdown menu')),
            ],
            options={
                'verbose_name': 'Company Page',
                'verbose_name_plural': 'Company Pages',
                'ordering': ['order'],
            },
        ),
    ]
