# Generated by Django 5.2.9 on 2025-12-07 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_companypage'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUsSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('overview', 'Company Overview'), ('mission_vision', 'Mission & Vision'), ('history', 'Company Story / History'), ('core_values', 'Core Values / Principles'), ('why_choose_us', 'Why Choose Us'), ('achievements', 'Achievements / Recognition'), ('call_to_connect', 'Closing / Call to Connect')], max_length=100)),
                ('heading', models.CharField(max_length=200)),
                ('content', models.TextField(help_text='You can use HTML here for rich content')),
                ('image', models.ImageField(blank=True, null=True, upload_to='about_us/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='AboutUsPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_title', models.CharField(default='About Us', max_length=200)),
                ('hero_image', models.ImageField(blank=True, null=True, upload_to='about_us/hero/')),
                ('hero_heading', models.CharField(blank=True, default='About AlienHouse', max_length=200)),
                ('hero_subtext', models.TextField(blank=True)),
                ('sections', models.ManyToManyField(related_name='pages', to='core.aboutussection')),
            ],
        ),
    ]
